apiVersion: v2
name: postgres-operator-service-template
description: k0rdent service template for "postgres-operator"
type: application
version: 1.14.0
dependencies:
  - name: k0rdent-catalog
    version: 1.0.0
    repository: oci://ghcr.io/k0rdent/catalog/charts
