apiVersion: k0rdent.mirantis.com/v1alpha1
kind: ClusterDeployment
metadata:
  name: adopted
  namespace: kcm-system
spec:
  template: adopted-cluster-{{ dash_version }}
  credential: adopted-credential
  config:
    clusterLabels:
      type: adopted
      group: demo
