st-charts:
  - name: postgres-operator
    version: 1.14.0
    dependencies:
    - name: postgres-operator
      version: 1.14.0
      repository: https://opensource.zalando.com/postgres-operator/charts/postgres-operator
