ingress-nginx:
  controller:
    service:
      annotations:
        service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: /healthz
    hostPort:
      enabled: true

open-webui:
  ollama:
    ollama:
      models:
        pull: [smollm:135m]
        run: [smollm:135m]
  ingress:
    enabled: true
    class: "nginx"
    host: 'openwebui.example.com'
