apiVersion: k0rdent.mirantis.com/v1alpha1
kind: ServiceTemplate
metadata:
  name: open-webui-5-20-0
  annotations:
    helm.sh/resource-policy: keep
spec:
  helm:
    chartSpec:
      chart: open-webui
      version: 5.20.0
      interval: 10m0s
      sourceRef:
        kind: HelmRepository
        name: k0rdent-catalog
