name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - '*'
    paths:
      - apps/**/data.yaml
      - mkdocs.yml
      - mkdocs/**
      - scripts/deploy_web.sh
      - .github/workflows/gh-pages-deploy.yml
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - apps/**/data.yaml
      - mkdocs/**
      - mkdocs.yml
      - scripts/deploy_web.sh
      - .github/workflows/gh-pages-deploy.yml

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure Git User
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r mkdocs/requirements.txt

      - name: Test web pages build
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "REPO: $GITHUB_CONTEXT"
          mkdocs build

      - name: Build and Deploy pages - fork
        if: github.repository != 'k0rdent/catalog' && github.ref != 'refs/heads/main'
        run: |
          SITE_URL=${{ vars.SITE_URL }} ./scripts/deploy_web.sh

      - name: Build and Deploy pages - k0rdent/catalog
        if: github.repository == 'k0rdent/catalog' && github.ref == 'refs/heads/main'
        run: |
          SITE_URL=${{ vars.SITE_URL }} ./scripts/deploy_web.sh
