name: Build Helm Charts

on:
  push:
    branches:
      - '*'
    paths:
      - apps/*/charts/**
      - .github/workflows/helm-chart-build.yml
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - apps/*/charts/**
      - .github/workflows/helm-chart-build.yml

permissions:
  packages: write
  contents: read

jobs:
  detect-updated-charts:
    uses: ./.github/workflows/reusable-detect.yml

  build:
    needs: detect-updated-charts
    if: ${{ needs.detect-updated-charts.outputs.changed_folders != '[]' }}
    uses: ./.github/workflows/reusable-build.yml
    with:
      registry: ghcr.io
      repository: ${{ github.repository_owner }}/${{ github.event.repository.name }}/charts
    secrets:
      ACTOR: ${{ github.actor }}
      TOKEN: ${{ secrets.GITHUB_TOKEN }}
